# Generated by Django 5.1.4 on 2025-01-17 18:40

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('numPieceID', models.CharField(max_length=50, unique=True)),
                ('typePieceID', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('prix', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=50)),
                ('carburant', models.CharField(max_length=50)),
                ('boitevitesse', models.CharField(max_length=50)),
                ('climatisation', models.BooleanField(default=True)),
                ('nbrRoues', models.IntegerField(default=4)),
                ('nbrPlaces', models.IntegerField(default=5)),
                ('nbrPortes', models.IntegerField(default=5)),
                ('kilometrage', models.FloatField()),
                ('cylindre', models.FloatField()),
                ('anneeFabrication', models.IntegerField()),
                ('anneeCirculation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLocation', models.DateTimeField()),
                ('datePaiement', models.DateTimeField()),
                ('dateSortie', models.DateTimeField()),
                ('dateRetour', models.DateTimeField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('adresseLivraison', models.CharField(default='Parking', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.client')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.location')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatSortie', models.CharField(max_length=255)),
                ('etatRetour', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.location')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Dommage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='dommages/')),
                ('location_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.location_vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.TextField()),
                ('traitement', models.TextField()),
                ('montant', models.IntegerField()),
                ('dateEntree', models.DateTimeField()),
                ('dateSortie', models.DateTimeField()),
                ('preuves', models.FileField(upload_to='maintenances/')),
                ('dommage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.dommage')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(max_length=255)),
                ('src', models.ImageField(upload_to='photos/')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dateEmission', models.DateTimeField()),
                ('dateValidite', models.DateTimeField()),
                ('src', models.FileField(upload_to='documents/')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.vehicule')),
            ],
        ),
    ]
