# Generated by Django 5.1.4 on 2025-01-18 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dateEmission', models.DateTimeField()),
                ('dateValidite', models.DateTimeField()),
                ('src', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Dommage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='dommages/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLocation', models.DateTimeField()),
                ('datePaiement', models.DateTimeField()),
                ('dateSortie', models.DateTimeField()),
                ('dateRetour', models.DateTimeField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('adresseLivraison', models.CharField(default='Parking', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatSortie', models.CharField(max_length=255)),
                ('etatRetour', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.TextField()),
                ('traitement', models.TextField()),
                ('montant', models.IntegerField()),
                ('dateEntree', models.DateTimeField()),
                ('dateSortie', models.DateTimeField()),
                ('preuves', models.FileField(upload_to='maintenances/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(max_length=255)),
                ('src', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('prix', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=50)),
                ('carburant', models.CharField(max_length=50)),
                ('boitevitesse', models.CharField(max_length=50)),
                ('climatisation', models.BooleanField(default=True)),
                ('nbrRoues', models.IntegerField(default=4)),
                ('nbrPlaces', models.IntegerField(default=5)),
                ('nbrPortes', models.IntegerField(default=5)),
                ('kilometrage', models.FloatField()),
                ('cylindre', models.FloatField()),
                ('anneeFabrication', models.IntegerField()),
                ('anneeCirculation', models.IntegerField()),
            ],
        ),
    ]
